# Starter pipeline
trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: 
    npm install
  displayName: 'npm install'
  workingDirectory: $(Build.SourcesDirectory)/zstudio-app

- task: CmdLine@2
  displayName: "npm build"
  inputs:
    script: |
      dir $(Build.SourcesDirectory)/zstudio-app/node_modules
      npm run-script build
    workingDirectory: $(Build.SourcesDirectory)/zstudio-app

# - task: ArchiveFiles@2
#   displayName: 'Archive files'
#   inputs:
#     rootFolderOrFile: '$(Build.SourcesDirectory)/zstudio-app/build'
#     includeRootFolder: false
#     archiveType: zip
#     archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
#     replaceExistingArchive: true


# - task: CopyPublishBuildArtifacts@1
#   inputs:
#     CopyRoot: '$(Build.SourcesDirectory)/zstudio-app/build'
#     Contents: '**'
#     ArtifactName: 'zstudio-$(Build.BuildId).zip'
#     ArtifactType: 'Container'

# - task: DownloadBuildArtifacts@0
#   inputs:
#     buildType: 'current'
#     downloadType: 'single'
#     artifactName: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
#     downloadPath: '$(System.ArtifactsDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'